-- DROP USER PACTUM;

CREATE USER PACTUM
-- IDENTIFIED BY <password>
;

CREATE SEQUENCE PACTUM.SQ_ACESSO INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999999999 NOCYCLE CACHE 20 ORDER ;

CREATE SEQUENCE PACTUM.SQ_ANEXO INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PACTUM.SQ_BASE_DADOS INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PACTUM.SQ_CARGA_BASE_DADOS INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PACTUM.SQ_CONVENIO INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PACTUM.SQ_EMAIL INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PACTUM.SQ_PERFIL_USUARIO INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PACTUM.SQ_PESQUISADOR INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE SEQUENCE PACTUM.SQ_USUARIO_SISTEMA INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER ;

CREATE TABLE "PACTUM"."ACESSO" 
   (	"ID" NUMBER(15,0) DEFAULT "PACTUM"."SQ_ACESSO".nextval NOT NULL ENABLE, 
	"ID_CONVENIO" NUMBER(15,0) NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER(15,0), 
	"OPERACAO" VARCHAR2(100), 
	"DATA" DATE DEFAULT sysdate NOT NULL ENABLE, 
	 CONSTRAINT "ACESSO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA" ;

CREATE UNIQUE INDEX "PACTUM"."ACESSO_PK" ON "PACTUM"."ACESSO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA" ;
  CREATE INDEX "PACTUM"."ACESSO_USUARIO_IDX" ON "PACTUM"."ACESSO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA" ;
  CREATE INDEX "PACTUM"."ACES_SISTEMA_IDX" ON "PACTUM"."ACESSO" ("ID_CONVENIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA" ;

COMMENT ON COLUMN PACTUM.ACESSO.ID IS 'Identificador único.';
COMMENT ON COLUMN PACTUM.ACESSO.ID_CONVENIO IS 'Identificador do sistema.';
COMMENT ON COLUMN PACTUM.ACESSO.ID_USUARIO IS 'Identificador do usuário.';

CREATE TABLE "PACTUM"."ANEXO" 
   (	"ID" NUMBER DEFAULT "PACTUM"."SQ_ANEXO".nextval NOT NULL ENABLE, 
	"NOME_ARQUIVO" VARCHAR2(1000 CHAR), 
	"MIME_TYPE" VARCHAR2(100 CHAR), 
	"EXTENSAO" VARCHAR2(10 CHAR), 
	"TAMANHO" NUMBER, 
	"ANEXO" BLOB, 
	"ID_CONVENIO" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"ID_BASE_DADOS" NUMBER, 
	 CONSTRAINT "ANEXO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" 
 LOB ("ANEXO") STORE AS SECUREFILE (
  TABLESPACE "PACTUM" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

CREATE UNIQUE INDEX "PACTUM"."ANEXO_PK" ON "PACTUM"."ANEXO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;
  CREATE UNIQUE INDEX "PACTUM"."SYS_IL0000216617C00006$$" ON "PACTUM"."ANEXO" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
;

CREATE TABLE "PACTUM"."BASE_DADOS" 
   (	"ID" NUMBER DEFAULT "PACTUM"."SQ_BASE_DADOS".nextval NOT NULL ENABLE, 
	"NUMERO_PROCEDIMENTO" VARCHAR2(40), 
	"ORGAO_ORIGEM" VARCHAR2(90), 
	"PERIODICIDADE" VARCHAR2(20), 
	"FONTE_OBTENCAO" VARCHAR2(40), 
	"CONTATOS" VARCHAR2(500), 
	"RESUMO" VARCHAR2(4000), 
	"ANOTACAO" VARCHAR2(4000), 
	"NOME_BASE" VARCHAR2(180), 
	"AVISO_VENCIMENTO" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE, 
	"EXCLUIDO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	"ULTIMA_DATA_EXTRACAO" DATE, 
	 CONSTRAINT "BASE_DADOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;

CREATE UNIQUE INDEX "PACTUM"."BASE_DADOS_PK" ON "PACTUM"."BASE_DADOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;
;

CREATE TABLE "PACTUM"."CARGA_BASE_DADOS" 
   (	"ID" NUMBER DEFAULT "PACTUM"."SQ_CARGA_BASE_DADOS".nextval NOT NULL ENABLE, 
	"DATA_EXTRACAO" DATE, 
	"DATA_INICIO" DATE, 
	"DATA_FIM" DATE, 
	"DATA_CARGA_RADAR" DATE, 
	"LAYOUT_ARQUIVO" VARCHAR2(4000), 
	"ANOTACAO" VARCHAR2(4000), 
	"TAMANHO_BASE" NUMBER, 
	"UNIDADE_TAMANHO" VARCHAR2(2), 
	"FORMATO_BASE" VARCHAR2(10), 
	"ID_BASE_DADOS" NUMBER, 
	"ID_ANEXO" NUMBER, 
	 CONSTRAINT "CARGA_BASE_DADOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;

CREATE UNIQUE INDEX "PACTUM"."CARGA_BASE_DADOS_PK" ON "PACTUM"."CARGA_BASE_DADOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;
;

CREATE TABLE "PACTUM"."CONVENIO" 
   (	"ID" NUMBER(15,0) DEFAULT "PACTUM"."SQ_CONVENIO".nextval NOT NULL ENABLE, 
	"SIGLA" VARCHAR2(20) NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(80), 
	"ORGAO_VINCULO" VARCHAR2(90), 
	"CONTATOS" VARCHAR2(500), 
	"DATA_INICIO_VIGENCIA" DATE, 
	"DATA_FIM_VIGENCIA" DATE, 
	"RESUMO" VARCHAR2(4000), 
	"NUMERO_PROCEDIMENTO" VARCHAR2(23), 
	"ANOTACAO" VARCHAR2(4000), 
	"EXCLUIDO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "SISTEMA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA" ;

CREATE UNIQUE INDEX "PACTUM"."SISTEMA_PK" ON "PACTUM"."CONVENIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA" ;

COMMENT ON COLUMN PACTUM.CONVENIO.ID IS 'Identificador único.';
COMMENT ON COLUMN PACTUM.CONVENIO.SIGLA IS 'Sigla do sistema.';
COMMENT ON COLUMN PACTUM.CONVENIO.DESCRICAO IS 'Descrição do sistema.';

CREATE TABLE "PACTUM"."EMAIL" 
   (	"ID" NUMBER DEFAULT "PACTUM"."SQ_EMAIL".nextval NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100 CHAR), 
	"ENVIAR_BASE_DADOS" VARCHAR2(1), 
	"ENVIAR_CONVENIO" VARCHAR2(1), 
	 CONSTRAINT "EMAIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;

CREATE UNIQUE INDEX "PACTUM"."EMAIL_PK" ON "PACTUM"."EMAIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;
;

CREATE TABLE "PACTUM"."PERFIL_USUARIO" 
   (	"ID" NUMBER DEFAULT "PACTUM"."SQ_PERFIL_USUARIO".nextval NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER NOT NULL ENABLE, 
	"PERFIL" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	 CONSTRAINT "PERFIL_USUARIO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;

CREATE UNIQUE INDEX "PACTUM"."PERFIL_USUARIO_PK" ON "PACTUM"."PERFIL_USUARIO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;
;

CREATE TABLE "PACTUM"."PESQUISADOR" 
   (	"ID" NUMBER(15,0) DEFAULT "PACTUM"."SQ_PESQUISADOR".nextval NOT NULL ENABLE, 
	"MATRICULA" NUMBER(5,0) NOT NULL ENABLE, 
	"ATUALIZADO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE, 
	 CONSTRAINT "PESQUISADOR_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "PACTUM"."USUARIO_PK" ON "PACTUM"."PESQUISADOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA" )  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA" ;

CREATE INDEX "PACTUM"."USUARIO_MATRICULA_IDX" ON "PACTUM"."PESQUISADOR" ("MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA" ;
  CREATE UNIQUE INDEX "PACTUM"."USUARIO_PK" ON "PACTUM"."PESQUISADOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PEDIDOS_DATA" ;

COMMENT ON COLUMN PACTUM.PESQUISADOR.ID IS 'Identificador único.';
COMMENT ON COLUMN PACTUM.PESQUISADOR.MATRICULA IS 'Matrícula do usuário cadastrado.';

CREATE TABLE "PACTUM"."QUARTZ_CLUSTER_CONTROL" 
   (	"DATA" DATE NOT NULL ENABLE, 
	 CONSTRAINT "QUARTZ_CLUSTER_CONTROL_PK" PRIMARY KEY ("DATA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;

CREATE UNIQUE INDEX "PACTUM"."QUARTZ_CLUSTER_CONTROL_PK" ON "PACTUM"."QUARTZ_CLUSTER_CONTROL" ("DATA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;
;

CREATE TABLE "PACTUM"."USUARIO_SISTEMA" 
   (	"ID" NUMBER DEFAULT "PACTUM"."SQ_USUARIO_SISTEMA".nextval NOT NULL ENABLE, 
	"MATRICULA" VARCHAR2(20 CHAR), 
	"NOME" VARCHAR2(65 CHAR), 
	"EMAIL" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CARGO" VARCHAR2(60 CHAR), 
	"ATIVO" VARCHAR2(1 CHAR) NOT NULL ENABLE, 
	"CODIGO_CARGO" VARCHAR2(8 CHAR), 
	 CONSTRAINT "USUARIO_SISTEMA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;

CREATE UNIQUE INDEX "PACTUM"."USUARIO_SISTEMA_PK" ON "PACTUM"."USUARIO_SISTEMA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "PACTUM" ;
;

CREATE OR REPLACE FORCE EDITIONABLE VIEW "PACTUM"."VW_PESSOAL" ("MATRICULA", "NOME", "CPF", "EMAIL1", "EMAIL2", "CARGO_CODIGO", "CARGO_DESCRICAO", "DDD_RESIDENCIAL", "TELEFONE_RESIDENCIAL", "DDD_COMERCIAL", "TELEFONE_COMERCIAL", "DDD_CELULAR", "TELEFONE_CELULAR", "LOTACAO_CODIGO", "LOTACAO_SIGLA", "LOTACAO_DESCRICAO", "LOTACAO_SIGLA_PR", "LOTACAO_UF", "DESLIGADO", "DT_NASCIMENTO", "TITULO_NR", "RG_NUMERO", "RG_ORGEMISSOR_SG", "RG_UF_SG") AS 
  SELECT a.matricula, a.nome, cpf_num_to_string(a.cpf), a.email_tabralho email1,
       a.email_pessoal email2,
       a.cd_cargo cargo_codigo,
       a.ds_cargo cargo_descricao,
       a.ddd_tel_res ddd_residencial,
       a.num_tel_res telefone_residencial, a.ddd_tel_com ddd_comercial,
       a.num_tel_com telefone_comercial,
       a.ddd_celular,
       a.num_tel_cel telefone_celular,
       a.cd_lotacao lotacao_codigo, a.sg_lotacao lotacao_sigla,
       a.ds_lotacao lotacao_descricao,
       a.sg_lotacao_oficial lotacao_sigla_pr, a.uf_lotacao lotacao_uf,
       a.st_ativo desligado,
       a.dt_nascimento,
       a.nr_titulo titulo_nr,
       a.num_rg RG_NUMERO,
       a.org_emissor_rg RG_ORGEMISSOR_SG,
       a.uf_org_emissor RG_UF_SG
  FROM tab_cadastro_servidor a;
;

CREATE OR REPLACE FUNCTION PACTUM.cpf_num_to_string(cpf IN NUMBER)
RETURN VARCHAR
IS 
cpf_string VARCHAR(11) := '';
tamanhoInicial number;
tamanhoFinal number := 11;

BEGIN
tamanhoInicial := length(to_char(cpf));
FOR Lcntr IN tamanhoInicial..tamanhoFinal - 1
LOOP
    cpf_string := CONCAT('0' , cpf_string);
END LOOP;
cpf_string := CONCAT(cpf_string, cpf);
RETURN cpf_string;
END;
;

CREATE OR REPLACE function PACTUM.SQUIRREL_GET_ERROR_OFFSET (query IN varchar2) return number authid current_user is      l_theCursor     integer default dbms_sql.open_cursor;      l_status        integer; begin          begin          dbms_sql.parse(  l_theCursor, query, dbms_sql.native );          exception                  when others then l_status := dbms_sql.last_error_position;          end;          dbms_sql.close_cursor( l_theCursor );          return l_status; end; 
;
